### ISSUE TITLE
Clean estimate_message_delivery_and_dispatch_fee and conversion parameter

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-messages-substrate#109]

**Comment by HackFisher** [comment]
Latest update, after topics of #101 etc, this could be useful, and should keep and reuse.

But current implementation may be able to simplified and cleaned.

**Comment by AsceticBear** [comment]
Looks like this have been solved in https://github.com/darwinia-network/darwinia-messages-substrate/pull/186
