### ISSUE TITLE
In parity-bridges-common, should we remove fund account existence assertion when send_message?

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-messages-substrate#110]
The account's address is `5HQn2URwTz6CPsZzbtPzm93KEza881uQ92rLRhtRzSLoA7ws`, currently when we send s2s message, we must ensure the existence of this account.
https://github.com/darwinia-network/parity-bridges-common/blob/main/modules/messages/src/instant_payments.rs#L65-L67

**Comment by wuminzhe** [comment]
the user account which sending s2s message need to have an existence balance? @xiaoch05

**Comment by xiaoch05** [comment]
> the user account which sending s2s message need to have an existence balance? @xiaoch05

No, the line has been changed. See https://github.com/darwinia-network/darwinia-messages-substrate/blob/main/modules/messages/src/instant_payments.rs#L89
It's the fund account.

**Comment by wuminzhe** [comment]
the fee-market has removed this check.
https://github.com/darwinia-network/darwinia-messages-substrate/blob/8c877be1c4078b7a1b7a6361037b8ff9db74d93c/modules/fee-market/src/s2s/payment.rs#L54
