### ISSUE TITLE
Another way would be directly iterate though RewardItem and calculate the value wanted. RewardBook can be removed then.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-messages-substrate#112]
Another way would be directly iterate though RewardItem and calculate the value wanted. RewardBook can be removed then.

_Originally posted by @HackFisher in https://github.com/darwinia-network/darwinia-messages-substrate/pull/89#discussion_r884616380_

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-messages-substrate/pull/89#discussion_r884615220

**Comment by AsceticBear** [comment]
This has been fixed in https://github.com/darwinia-network/darwinia-messages-substrate/pull/169
