### ISSUE TITLE
Remove/simplify relay folder after bridger s2s refactor

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-messages-substrate#124]
https://github.com/darwinia-network/bridger/pull/467  

Review and remove `latest_updated_confirm_nonce_at_source` together.

**Comment by HackFisher** [comment]
Message rpc api can also be removed.

**Comment by fewensa** [comment]
Fixed by https://github.com/darwinia-network/darwinia-messages-substrate/pull/149
