### ISSUE TITLE
Add integration docs to the repo

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-messages-substrate#16]
https://itering.notion.site/How-to-Develop-a-Substrate-to-Substrate-Bridge-98b50a6e96774c1984d606a549f0a550

**Comment by HackFisher** [comment]
Add the convention of dependency management for bridges and (third party) chains to follow.

![Substrate_dependency drawio (1)](https://user-images.githubusercontent.com/1070122/160096535-b59ca30a-9187-4825-93fc-66c27871bfbd.png)

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-bridges-substrate/tree/main/bin/runtime-common

**Comment by wuminzhe** [comment]
I will try to build a bridge from scratch. Any suggestion?

**Comment by AsceticBear** [comment]
On the node side, you can run a pangolin <> pangoro network locally and figure out the configuration of those two chains' runtime(bridges-grandpa, bridges-messages, bridges-dispatch, bridges-fee-market), here is a script https://github.com/darwinia-netwrk/darwinia-common#development to help you set up node easier. In addition, you also need to run a bridger, follow the README and have a try.
