### ISSUE TITLE
Mandatory header relay should not pay fees.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-messages-substrate#167]
https://crab.subscan.io/extrinsic/0x7ca64cf17a8396bae2fcb53f238355b34ecf9d18db7a583e7e2bcef9ea7da919

Why relay mandatory headers is paying fees actually.

**Comment by wuminzhe** [comment]
I saw that the Consensus `GRANDPA_ENGINE_ID` used to filter log is `FRNK`, but the header's Consensus engine id is `BABE`.

**Comment by AurevoirXavier** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/16152305/181472275-30c77d64-ba6e-4669-aba8-65ea3c7961df.png">

Fold the first one up.

**Comment by wuminzhe** [comment]
Yes, there are two Consensus item

**Comment by HackFisher** [comment]
What this tx has duplicate Deposit event:

https://pangolin.subscan.io/extrinsic/3426340-1

**Comment by HackFisher** [comment]
> What this tx has duplicate Deposit event:
> 
> https://pangolin.subscan.io/extrinsic/3426340-1

https://github.com/darwinia-network/darwinia-common/issues/914

**Comment by HackFisher** [comment]
There is a Deposit back to TX sender, so no fee charged.

Related: https://github.com/darwinia-network/darwinia/issues/925
