### ISSUE TITLE
Question about market fee design from zola

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-messages-substrate#180]
> 有个设计策略上的疑问，如果in slot的情况，按惩罚比例20% 固定* 某Relayer的保证金，那么，从Relayer的角度，是不是会更倾向于保证金只按最低来交呢？ （这样可以slash更少） 而保证金交的少，会造成他保证金更容易被slash完导致relayer inactive的情况。这样对系统稳定性不太有利？以relayer个人保证金 作为惩罚基数，再乘上一个固定比例的方式，不确定是不是会有些问题  

https://www.notion.so/itering/What-Can-A-Cross-Chain-Message-Relayer-Get-2a37daa552664df0a1e9b15ed76856f0#80c02cce252b4bd3b4b4030b5865e5f8

@ZolaxZola @AsceticBear @1022ranji @HackFisher

**Comment by HackFisher** [comment]
For the base of 20%, should be the collateral per order.
