### ISSUE TITLE
`increase_message_fee` is not applicable to the fee-market design.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-messages-substrate#205]
In the `fee-market` design, the fee of `send_message` is required by the top relayers maker fee.
The interface of [increase_message_fee](https://github.com/paritytech/parity-bridges-common/blob/816ddd2dd2239012c6fd08b984bf4d97d5399131/modules/messages/src/lib.rs#L292) is not applicable for the design.

**Comment by AsceticBear** [comment]
Okay. I'll finish this issue this week.
